FROM 700843992353.dkr.ecr.us-east-1.amazonaws.com/sagemaker-distribution-staging-repository:3.5.4-gpu

COPY ./dirs/etc/patches/smus/0002-sparkmagic-override-info-table.patch /etc/patches/smus/0002-sparkmagic-override-info-table.patch
RUN micromamba install sagemaker-studio-dataengineering-sessions==1.3.11
