FROM public.ecr.aws/sagemaker/sagemaker-distribution:2.9.1-cpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=$IMAGE_VERSION
ENV IMAGE_VERSION=2.9.2-cpu
LABEL "org.amazon.sagemaker-distribution.image.version"=2.9.2-cpu

RUN micromamba install 'sagemaker-gen-ai-jupyterlab-extension>=1.0.8' -y -n base
