# Run: conda env update --file environment.yml -n sagemaker-distribution
channels:
  - conda-forge
dependencies:
  - conda
  - docker-py
  - pip
  - boto3
  - pytest
  - pytest-mock
  - pytest-xdist
  - semver
  - autoflake
  - black
  - isort
  - pre-commit
  - condastats>=0.2.1
  - s3fs>=2025.3.2
