FROM public.ecr.aws/sagemaker/sagemaker-distribution:2.9.2-gpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=$IMAGE_VERSION
ENV IMAGE_VERSION=2.9.3-gpu
LABEL "org.amazon.sagemaker-distribution.image.version"=2.9.3-gpu

CMD micromamba install 'sagemaker-studio-dataengineering-extensions>=1.2.9' -y -n base
