name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug.

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/aws/sagemaker-distribution/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: dropdown
  id: category
  attributes:
    label: Category
    description: What is the type of the bug?
    options:
      - Compatibility Issue
      - Image Size Issue
      - Performance Issue
      - Usability Issue
      - Others
  validations:
    required: true
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc.

      Please also paste or describe the results you observe.
      If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is. If you have a screenshot of the issue, please upload it here.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: false
- type: textarea
  attributes:
    label: 🐛 Describe the expected behavior
    description: |
      Please provide a clear and concise description of the expected behaviors.
  validations:
    required: false
- type: textarea
  attributes:
    label: Image Tags
    description: |
      Please specify which image versions you reproduced the issue on. (e.g. 1.6.1-cpu)
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
