FROM public.ecr.aws/sagemaker/sagemaker-distribution:2.11.0-cpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=2.11.1-cpu
LABEL "org.amazon.sagemaker-distribution.image.version"=2.11.1-cpu
RUN micromamba install -y -n base sagemaker-jupyterlab-extension-common==0.2.14

