FROM public.ecr.aws/sagemaker/sagemaker-distribution:2.9.8-cpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=2.9.9-cpu
LABEL "org.amazon.sagemaker-distribution.image.version"=2.9.9-cpu
RUN micromamba install -y -n base sagemaker-jupyterlab-extension-common==0.2.14

