FROM public.ecr.aws/sagemaker/sagemaker-distribution:3.3.1-cpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=3.3.2-cpu
LABEL "org.amazon.sagemaker-distribution.image.version"=3.3.2-cpu

RUN sudo rm /etc/patches/smus/0003-fix-ipython-display.patch
