FROM public.ecr.aws/sagemaker/sagemaker-distribution:2.9.5-cpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=2.9.6-cpu
LABEL "org.amazon.sagemaker-distribution.image.version"=2.9.6-cpu

RUN micromamba install -y -n base 'sagemaker-studio-dataengineering-extensions==1.2.13' 'ipykernel<7' 
