FROM 700843992353.dkr.ecr.us-east-1.amazonaws.com/sagemaker-distribution-staging-repository:2.12.0-cpu

RUN micromamba -n base install sagemaker-studio-dataengineering-sessions==1.3.11 'jupyterlab<4.5.0'
