FROM 700843992353.dkr.ecr.us-east-1.amazonaws.com/sagemaker-distribution-staging-repository:2.12.0-gpu

RUN micromamba install -n base sagemaker-studio-dataengineering-sessions==1.3.11 'jupyterlab<4.5.0'
