FROM public.ecr.aws/sagemaker/sagemaker-distribution:3.4.5-cpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=3.4.6-cpu
LABEL "org.amazon.sagemaker-distribution.image.version"=3.4.6-cpu

RUN micromamba install -y -n base 'sagemaker-studio-dataengineering-extensions==1.2.13' 
