FROM public.ecr.aws/sagemaker/sagemaker-distribution:3.4.8-gpu

ARG IMAGE_VERSION
ENV IMAGE_VERSION=3.4.9-gpu
LABEL "org.amazon.sagemaker-distribution.image.version"=3.4.9-gpu
RUN micromamba install -y -n base sagemaker-jupyterlab-extension-common==0.2.14

