FROM public.ecr.aws/sagemaker/sagemaker-distribution:3.4.0-gpu

ENV IMAGE_VERSION=3.4.1-gpu
LABEL "org.amazon.sagemaker-distribution.image.version"=3.4.1-gpu

RUN sudo rm /etc/patches/smus/0003-fix-ipython-display.patch
