name: Build New Image Version (Beta)
on: 
  workflow_dispatch:
  # Run every night at 4:00PM PDT
  schedule:
    - cron: '0 23 * * *'
defaults:
  run:
    shell: bash -l {0}
jobs:
  call-codebuild-project:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.START_CODEBUILD_ROLE }}
          aws-region: us-east-1
          # CodeBuild timeout of 8 hours
          role-duration-seconds: 28800
          audience: https://sts.us-east-1.amazonaws.com
      - name: Run CodeBuild
        uses: dark-mechanicum/aws-codebuild@v1
        with:
          projectName: 'betaimagerelease92AD4800-5O3Rv5xogtpw'
          buildspec: '{"imageOverride": "aws/codebuild/standard:7.0", "imagePullCredentialsTypeOverride": "CODEBUILD"}'
