# Workflow manually triggered to stop nightly builds for a given image version.
name: Stop Nightly Build
run-name: Stop Nightly Build (${{ inputs.version }})
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to stop building (x.y.z, e.g. 3.0.0)'
                required: true
                type: string
defaults:
    run:
        shell: bash -l {0}
jobs:
    update-nightly-schedule:
        name: Update nightly_build_schedule.json
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mamba-org/setup-micromamba@v1
              with:
                environment-file: ./environment.lock
                environment-name: sagemaker-distribution
                init-shell: bash
            - name: Update nightly_build_schedule.json
              id: update-schedule
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                micromamba activate sagemaker-distribution
                echo '${{ vars.NIGHTLY_BUILD_SCHEDULE }}' > schedule.json
                python ./.github/workflows/utils/nightly_build_helper.py remove-version \
                  ${{ inputs.version }} --current-schedule-file schedule.json
                gh variable set NIGHTLY_BUILD_SCHEDULE < schedule.json
                echo Successfully set NIGHTLY_BUILD_SCHEDULE environment variable: https://github.com/aws/sagemaker-distribution/settings/variables/actions
