# Workflow manually triggered to stop nightly builds for a given image version.
name: Stop Nightly Build
run-name: Stop Nightly Build (${{ inputs.version }})
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to stop building (x.y.z, e.g. 3.0.0)'
                required: true
                type: string
concurrency:
    group: schedule-update
    cancel-in-progress: false
defaults:
    run:
        shell: bash -l {0}
jobs:
    update-nightly-schedule:
        name: Update nightly build schedule
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mamba-org/setup-micromamba@v2
              with:
                environment-file: ./environment.lock
                environment-name: sagemaker-distribution
                init-shell: bash
            - name: Update nightly_build_schedule.json
              id: update-schedule
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                micromamba activate sagemaker-distribution
                python ./.github/workflows/utils/nightly_build_helper.py remove-version ${{ inputs.version }}